apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caddy-homelab-caddy-ingress-controller
spec:
  defaultBackend:
    service:
      name: caddy-homelab-caddy-ingress-controller
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - caddy
