apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caddy-homelab-caddy-ingress-controller
spec:
  defaultBackend:
    service:
      name: caddy-homelab-caddy-ingress-controller
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - caddy

helm upgrade \
  --install \
  tailscale-operator \
  tailscale/tailscale-operator \
  --namespace=tailscale \
  --create-namespace \
  --set-string oauth.clientId=k1ggyXS7SX11CNTRL \
  --set-string oauth.clientSecret=tskey-client-k1ggyXS7SX11CNTRL-yYy3Ee3z5oaZ1q97M8vRtaKjW6gCbU9Bh \
  --wait
